### ISSUE TITLE
CircleCI Review

### ISSUE THREAD

**Issue by KyleTryon** [k6io/circleci-orb#1]
Hello All,

My name is Kyle from the CircleCI Community and Partner Engineering team following up on my email with some review items on the current orb.

1. If the command is not meant to be used by end-users, do not create it.
  a. Instead, simply contain all logic within the job. No commands are needed.
  b. https://github.com/k6io/circleci-orb/blob/main/src/commands/run-test.yml
2. Allow the user to specify a specific docker tag.
  a. https://github.com/k6io/circleci-orb/blob/a1ae46a30dcd2fd80640c3a98f2fb3c95f1771fe/src/jobs/test.yml#L4
  b. Parameterize the tag portion of the docker image.
  c. Specifying a tag is important for CI so users can test against known and good versions.
  e. Example: https://github.com/CircleCI-Public/node-orb/blob/3d313ec2fbc9dd2a5c804d9b142e2419c4176ca4/src/executors/default.yml#L14
3. Private information should be accessed via environment variables, not hard-coded strings in the config.
  a. https://github.com/k6io/circleci-orb/blob/a1ae46a30dcd2fd80640c3a98f2fb3c95f1771fe/src/jobs/test.yml#L23
  b. https://circleci.com/docs/2.0/orb-author-faq/?section=configuration#secure-api-tokens

**Comment by simskij** [comment]
@KyleTryon Thanks a bunch for the review! I just pushed a new version of the orb to both GitHub and the orb registry, which I think takes care of the items on your list. Would you mind having another look?

**Comment by KyleTryon** [comment]
@simskij In the future, I recommend utilizing pull requests from another to implement changes. This way, the dev version can be updated automatically and tested prior to merging changes to main. This also gives you the opportunity to designate what type of orb update to make to the registry (if providing a production update).

I do not see your orb listed on the registry yet: https://circleci.com/orbs/registry/orb/k6io/circleci-orb
We will get this published be merging a PR to main with `[semver:major]` in the title.

https://circleci.com/docs/2.0/creating-orbs/#issue-a-new-release

---

Review items:

- The orb imports itself:
  - https://github.com/k6io/circleci-orb/blob/2c22c549363229023d06395de32e7b20480d8d58/src/%40orb.yml#L11
  - The orb should not be importing itself here. This is in case your orb relies on components from other orbs. For instance, the AWS orbs often rely on the AWS CLI orb to install the AWS CLI.
- Update README
- Update About Section
- Add website link to orb registry under about

---

The first item above appears to be the only required change.  Let's issue this change and publish version 1.0.0 publically to the orb registry using the [method mentioned above](https://circleci.com/docs/2.0/creating-orbs/#issue-a-new-release).

Once the change is made and the orb is published we should be good to go 👍
